name: Build and Deploy Spring Boot App to Server.
on:
  push:
    branches:
      - test
  workflow_dispatch:

env:
  JAVA_VERSION: '17'
  # APP_PORT: 8080
  APP_NAME: 'biassist-web-ui'
  REPO_PATH: '/mnt/app'
  JAR_NAME: 'biassist-web-ui.jar'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          cache: 'maven'

      - name: Cache Maven packages
        id: cache-maven
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build application with Maven
        run: mvn clean package -DskipTests --batch-mode

      - name: Copy JAR to Staging VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          source: "target/*.jar"
          target: ${{ env.REPO_PATH }}
          # rm: true
          overwrite: true

      - name: Deploy on Staging VM
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST}}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD}}
          port: ${{ secrets.PORT }}
          command_timeout: 20m
          script: |
            set -e
            echo "🚀 Starting deployment"
            cd ${{ env.REPO_PATH }}

            # echo "🛑 Stopping existing application..."
             pm2 stop ${{ env.APP_NAME }} 2>/dev/null || true

            echo "🚀 Starting Spring Boot app with PM2..."
             pm2 start "java -jar target/*.jar" \
                 --name "biassist-web-ui" \
                 --no-autorestart 2>/dev/null || \
             pm2 restart biassist-web-ui

            pm2 save --force
            sleep 10

            echo "✅ Verifying application..."
            # pm2 status
            # pm2 logs ${{ env.APP_NAME }} --lines 20 --nostream
